version: "2"

services:
  cloudflared:
    container_name: cloudflared
    image: visibilityspots/cloudflared:latest
    restart: unless-stopped
    command: "/usr/local/bin/cloudflared proxy-dns --address 0.0.0.0 --port 5054 --upstream https://9.9.9.9:5053/dns-query --upstream https://1.1.1.1/dns-query"
    networks:
      pihole_net:
        ipv4_address: 10.0.0.2
    environment:
      - DNS1=9.9.9.9
      - DNS2=9.9.9.11

  pi-hole:
    container_name: pi-hole
    image: pihole/pihole:latest
    restart: unless-stopped
    #stdin_open: true
    #    tty: true
    ports:
      - "22222:443/tcp"
      - "22223:80/tcp"
      - "53:53/udp"
    environment:
      - ServerIP=10.0.0.3
      - PIHOLE_DNS_=10.0.0.2#5054
      - IPv6=false
      - TZ=America/New_York
      - DNSMASQ_LISTENING=all
      - WEBPASSWORD=admin
    networks:
      pihole_net:
        ipv4_address: 10.0.0.3
    dns:
      - 127.0.0.1
    cap_add:
      - NET_ADMIN
    volumes:
      - '/home/ubuntu/pihole/data/etc-pihole/:/etc/pihole/'
      - '/home/ubuntu/pihole/data/etc-dnsmasq.d/:/etc/dnsmasq.d/'

networks:
  pihole_net:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/29
